### ISSUE TITLE
.npmignore is not restored after npm pack

### ISSUE THREAD

**Issue by ckreddybh** [kleingtm/npm-pack-all#5]
https://github.com/kleingtm/npm-pack-all/blob/master/index.js#L56
shell.rm(`-Rf`, `.npmignore`);

**Comment by kleingtm** [comment]
Thanks for the heads up. Let me know if upgrading to 1.11.1 fixes it: [](https://github.com/kleingtm/npm-pack-all/compare/d9e5ceec1b84...87e0a94ccc83)
