### ISSUE TITLE
Specifying --output with a scoped package name is broken

### ISSUE THREAD

**Issue by thethorne48** [kleingtm/npm-pack-all#9]
# Issue

When using scoped packages and attempting to build to a output directory, the name of the zip is modified to no include path separators but the `mv` command doesn't recognize that change and attempts to move a zip from under the `@scopedname` directory.

## Config
example package.json
```json
{
    "name": "@scopedname/some-project",
    "version": "1.1.1",
    "description": "Some description",
    "main": "index.js",
    "scripts": {
        "build": "node node_modules/npm-pack-all --output build/artifact.tgz"
    },
}
```

## Reproduce

Running `npm run build` results in this error:
`Error: mv: no such file or directory: Path/to/my/root/@scopedname/some-project-1.1.1.tgz`

This is because the tgz file is renamed to `scopedname-some-project-1.1.1.tgz` but the mv command is attempting to move the scoped filename.

**Comment by kleingtm** [comment]
Fixed and tested.
